const dotenv = require("dotenv");
dotenv.config();
const {
  APP_PORT,
  MAX_JSON_SIZE,
  URL_ENCODE,
  REQUEST_TIME,
  REQUEST_NUMBER,
  WEB_CACHE,
  DATABASE,
  JWT_KEY,
  JWT_EXPIRE_TIME,
  EMAIL_HOST,
  EMAIL_PORT,
  EMAIL_SECURITY,
  EMAIL_USER,
  EMAIL_PASS,
} = process.env;

module.exports = {
  APP_PORT,
  MAX_JSON_SIZE,
  URL_ENCODE,
  REQUEST_TIME,
  REQUEST_NUMBER,
  WEB_CACHE,
  DATABASE,
  JWT_KEY,
  JWT_EXPIRE_TIME, //30*24*60*60
  EMAIL_HOST,
  EMAIL_PORT,
  EMAIL_SECURITY,
  EMAIL_USER,
  EMAIL_PASS,
};

